name: flutter_phone_state
description: This plugin provides an easy way to make phone calls, and track the state of the phone call
version: 2.0.0
homepage: "https://github.com/SunnyApp/flutter_phone_state.git"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.0.1
  stream_transform: ^2.0.0
  url_launcher: ^6.0.9
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  plugin:
    platforms:
      android:
        package: co.sunnyapp.flutter_phone_state
        pluginClass: FlutterPhoneStatePlugin
